#!/usr/bin/env python3
"""
Prepare site-ready data from scraped referendum results.
Updated to work with the Simplified API Scraper.
"""

import argparse
import json
import sys
from pathlib import Path
import pandas as pd

def load_data(csv_path: Path) -> pd.DataFrame:
    # Load the CSV generated by the new simplified scraper
    df = pd.read_csv(csv_path, low_memory=False)

    # 1. Ensure all numerical columns are safe floats/ints
    cols_to_check = ["yes", "no", "sections_reported", "sections_total", "electors", "yes_pct", "no_pct"]
    for c in cols_to_check:
        if c in df.columns: 
            df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0)
        else: 
            df[c] = 0

    # 2. FIX FOR APP.JS: The new scraper doesn't fetch turnout. 
    # We must calculate a 'best_perc' (turnout) based on counted votes to prevent the site from crashing.
    df["best_perc"] = 0.0
    mask = df["electors"] > 0
    df.loc[mask, "best_perc"] = ((df.loc[mask, "yes"] + df.loc[mask, "no"]) / df.loc[mask, "electors"]) * 100

    # 3. Fill missing text columns to prevent grouping errors
    for c in ["region", "province", "comune", "state"]:
        if c not in df.columns:
            df[c] = "Sconosciuto"
        df[c] = df[c].fillna("Sconosciuto")

    return df

def enrich(df: pd.DataFrame) -> pd.DataFrame:
    # Calculate progress safely
    df["progress"] = 0.0
    mask = df["sections_total"] > 0
    df.loc[mask, "progress"] = df.loc[mask, "sections_reported"] / df.loc[mask, "sections_total"]
    
    # Ensure 'state' is present for the frontend
    if "state" not in df.columns:
        df["state"] = df["progress"].apply(lambda x: "final" if x >= 1 else "counting")
        
    return df

def compute_totals(df: pd.DataFrame) -> dict:
    total_yes = df["yes"].sum()
    total_no = df["no"].sum()
    total_votes = total_yes + total_no
    
    electors = df["electors"].sum()
    avg_turnout = (total_votes / electors * 100) if electors > 0 else 0.0

    return {
        "yes": int(total_yes),
        "no": int(total_no),
        "yes_pct": float(total_yes / total_votes * 100) if total_votes else 0.0,
        "no_pct": float(total_no / total_votes * 100) if total_votes else 0.0,
        "best_perc": float(avg_turnout),  # Protects app.js
        "sections_reported": int(df["sections_reported"].sum()),
        "sections_total": int(df["sections_total"].sum()),
        "progress": float(df["sections_reported"].sum() / df["sections_total"].sum()) if df["sections_total"].sum() > 0 else 0.0,
    }

def group_by_region(df: pd.DataFrame) -> list[dict]:
    grouped = []
    for region_name, g in df.groupby("region"):
        totals = compute_totals(g)
        grouped.append({"region": region_name, **totals})
    return grouped

def group_by_province(df: pd.DataFrame) -> list[dict]:
    grouped = []
    for (region, province), g in df.groupby(["region", "province"]):
        totals = compute_totals(g)
        grouped.append({"region": region, "province": province, **totals})
    return grouped

def build_comuni(df: pd.DataFrame) -> list[dict]:
    cols = [
        "region", "province", "comune", "yes", "no", 
        "yes_pct", "no_pct", "sections_reported", 
        "sections_total", "progress", "state"
    ]
    existing_cols = [c for c in cols if c in df.columns]
    return df[existing_cols].to_dict(orient="records")

def main():
    parser = argparse.ArgumentParser(description="Prepare referendum results JSON")
    parser.add_argument("--csv", required=True, help="Path to scraper CSV")
    parser.add_argument("--output-dir", default="docs/data", help="Output directory")
    
    # CI Flags to stop GitHub Actions from crashing
    parser.add_argument("--skip-boundaries", action="store_true", help="CI flag")
    parser.add_argument("--boundaries", help="CI flag")
    
    args = parser.parse_args()

    csv_path = Path(args.csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not csv_path.exists():
        print(f"Error: {csv_path} not found. Ensure the scraper ran successfully.")
        sys.exit(1)

    print(f"Reading {csv_path}...")
    df = load_data(csv_path)

    print("Processing results...")
    df = enrich(df)

    print("Generating summaries...")
    national = compute_totals(df)
    regions = group_by_region(df)
    provinces = group_by_province(df)
    comuni = build_comuni(df)

    # Save outputs safely
    (output_dir / "national.json").write_text(json.dumps(national, indent=2))
    (output_dir / "regions.json").write_text(json.dumps(regions, indent=2))
    (output_dir / "provinces.json").write_text(json.dumps(provinces, indent=2))
    (output_dir / "comuni.json").write_text(json.dumps(comuni, indent=2))

    print(f"Done ✅ Files saved to {output_dir}/. Ready for the frontend!")

if __name__ == "__main__":
    main()